/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2022 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

// This is a partial file designed to be included by other files when
// constructing various tables.

XE_MODULE_EXPORT_GROUP(xboxkrnl, Audio)
XE_MODULE_EXPORT_GROUP(xboxkrnl, AudioXma)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Crypt)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Debug)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Error)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Hal)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Hid)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Io)
XE_MODULE_EXPORT_GROUP(xboxkrnl, IoInfo)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Memory)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Misc)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Module)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Ob)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Rtl)
XE_MODULE_EXPORT_GROUP(xboxkrnl, String)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Threading)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Usbcam)
XE_MODULE_EXPORT_GROUP(xboxkrnl, Video)
XE_MODULE_EXPORT_GROUP(xboxkrnl, XConfig)
