# Copyright 2013 Ben Vanik. All Rights Reserved.
{
  'sources': [
    'xam_content.cc',
    'xam_content.h',
    'xam_info.cc',
    'xam_info.h',
    'xam_input.cc',
    'xam_input.h',
    'xam_module.cc',
    'xam_module.h',
    'xam_net.cc',
    'xam_net.h',
    'xam_notify.cc',
    'xam_notify.h',
    'xam_ordinals.h',
    'xam_private.h',
    'xam_state.cc',
    'xam_state.h',
    'xam_table.inc',
    'xam_user.cc',
    'xam_user.h',
    'xam_video.cc',
    'xam_video.h',
  ],
}
